// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/dimuska139/golang-api-skeleton/api"
	"github.com/dimuska139/golang-api-skeleton/config"
	"github.com/dimuska139/golang-api-skeleton/database"
	"github.com/dimuska139/golang-api-skeleton/services"
)

// Injectors from wire.go:

func InitializeUsersAPI(configPath string) (*api.UsersAPI, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	db, err := database.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	usersService := services.NewUsersService(db)
	usersAPI := api.NewUsersAPI(usersService)
	return usersAPI, nil
}
